# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'StarWar' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.0'
  # Pods for StarWar

  target 'StarWarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarWarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
