# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Pokemon' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 3.0'

  # Pods for Pokemon

end
